config/routes.rb
Rails.application.routes.draw do
  get 'informations/index'

  get 'categories/index'

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'static_pages#home'

  get  'help'   => 'static_pages#help'
  get  'about'   => 'static_pages#about'
  get  'contact' => 'static_pages#contact'

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: :show  
  resources :vehicle_models
  resources :vehicle_brands, only: [:index, :show]
  resources :options
  resources :advertisements do
    resources :comments do
      put 'upvote', to: 'comments#upvote'
    end
  end


  resources :categories, only: [:index, :show] do
    member do
      get "basic", to: "categories#basic"
      get "additional", to: "categories#additional"
      get "options", to: "categories#options"

      resources :advertisements, only: :show 
    end
  end

  resources :information, only: :index do
    member do
      get 'items', to: 'informations#items'  
    end  
  end
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
	extend FriendlyId

	belongs_to :advertisement_type
	belongs_to :user, validate: true
	belongs_to :category, validate: true
	belongs_to :vehicle_model, validate: true
	has_and_belongs_to_many :options, autosave: true
	has_many :advertisement_informations, autosave: true, dependent: :destroy
	has_many :informations, through: :advertisement_informations
	has_many :comments

	# this creates advertisement_informations_attributes= method on Advertisement that allows
	# create, update and delete destroy advertisement_informations
	accepts_nested_attributes_for :advertisement_informations
	accepts_nested_attributes_for :options

	serialize :images, Array
	# picture - name of the attribute
	mount_uploaders :images, ImageUploader

	validates :title, presence: true
	validates :price, presence: true
	validates :year, presence: true
	validates :vehicle_model, presence: true
	validates :user, presence: true

	friendly_id :title, use: [:slugged, :finders]

	scope :active, -> { where('status =', self.active) }

	enum status: [:active, :inactive, :pending, :rejected]

	# TODO - ovo refaktorisati
	def save_all advertisement_informations
		advertisement_informations ||= {}
		
	  	advertisement_informations.each do |info_id, value|
	  		a = AdvertisementInformation.create(
	        			advertisement: self,
	        			information: Information.find(info_id),
	        			value: value
	      			)
	  		self.advertisement_informations << a
	  	end

	  	self.pending!
		saved = self.save
  		
		return saved
	end

	def update_all(advertisement_params, informations)
		self.advertisement_informations.each do |info|
			informations.each do |key, value|
				if key.to_i == info.information_id.to_i
					info.value = value
				end
			end
		end

		return self.update(advertisement_params)
	end

	def get_information type
		id = InformationType.find_by(name: type).id
		arr = []

		informations.each do |info|
			if info.information_type_id == id
  			arr << info
  		end
		end

		return arr
	end

	# filter out empty options
	def self.get_options params
		arr = params.to_a
		ret_val = []

		arr.each do |el|
			if el[1]["name"].count == 2 && el[1]["name"].include?("1")
				ret_val << el[1]["id"].to_i
			end
		end

		return ret_val
	end

	def slug_candidates
    [
      :title,
      [:title, :year],
      [:title, :year, :price]
    ]
  end

end

app/models/advertisement_type.rb
class AdvertisementType < ActiveRecord::Base
	has_many :advertisements

	validates :name, presence: true
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show

  load_and_authorize_resource only: [:edit, :update, :destroy]

  def index
    @advertisements = Advertisement.where('user_id = ?', current_user.id)
  end

  def show
    @basic_advertisement_informations = {}
    @additional_advertisement_informations = {}
    basic_information_id = InformationType.find_by(name: "Basic").id
    additional_information_id = InformationType.find_by(name: "Additional").id

    @advertisement.informations.each do |info|
      if info.information_type.id == basic_information_id
        @basic_advertisement_informations[info.name] = ""
      elsif info.information_type.id == additional_information_id
        @additional_advertisement_informations[info.name] = ""
      end
    end

    @advertisement.advertisement_informations.each do |adv_info|
      if @basic_advertisement_informations.has_key?(adv_info.information.name)
        @basic_advertisement_informations[adv_info.information.name] = adv_info.value
      elsif @additional_advertisement_informations.has_key?(adv_info.information.name)
        @additional_advertisement_informations[adv_info.information.name] = adv_info.value
      end
    end

    @options = @advertisement.options
    # TODO: ovo istestirati
    @comments = @advertisement.comments
  end

  def new
    @advertisement = Advertisement.new
    @categories = Category.all
  end

  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.user = current_user
    @advertisement.option_ids = params[:advertisement][:options_attributes]
    #advertisement_informations = params[:advertisement][:advertisement_informations]
    advertisement_informations = get_advertisement_informations params[:advertisement][:advertisement_informations]

    if @advertisement.save_all(advertisement_informations)
      UserMailer.advertisement_created(current_user.email, @advertisement.id).deliver_now
      flash[:success] = "Advertisement successfully created."
      redirect_to @advertisement
    else
      render :new
    end
  end

  def edit
    @basic_informations = Category.get_all_category_informations(@advertisement.category.id, "Basic")
    @additional_informations = Category.get_all_category_informations(@advertisement.category.id, "Additional")
    @all_options = @advertisement.category.options
  end

  def update
    informations = get_advertisement_informations params[:advertisement][:advertisement_informations]
    @advertisement.option_ids = Advertisement.get_options params[:advertisement][:options_attributes]

    if @advertisement.update_all(advertisement_params, informations)
      flash[:success] = "Advertisement successfully updated."
      redirect_to @advertisement
    else
      @basic_informations = Category.get_all_category_informations(@advertisement.category.id, "Basic")
      @additional_informations = Category.get_all_category_informations(@advertisement.category.id, "Additional")
      @all_options = @advertisement.category.options#

      flash.now[:notice] = "ERROR: Updating advertisement.Please try again.Thank you!"
      render :edit
    end
  end

  def destroy
    @advertisement.destroy

    redirect_to advertisements_path
  end

  private

  def set_advertisement
    #@advertisement = Advertisement.find(params[:id])
    @advertisement = Advertisement.friendly.find(params[:id])
  end

  def advertisement_params
    params.require(:advertisement).permit(:title, :description, :price, :year, :category_id,
                                          :vehicle_model_id, :user_id, :advertisement_type_id,
                                          :option_ids, :advertisement_informations, images: [])
  end

  # we have to check is Item with given id exists or is it a value
  def get_advertisement_informations(in_params)
    in_params ||= []
    ret_arr = {}
    in_params.each do |key, value|
      value = (Item.exists?(value) ? value = Item.find(value).name : value)
      ret_arr[key] = value
    end

    return ret_arr
  end

end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/_advertisement.html.erb
<tr>
	<td><%= advertisement.title %></td>
	<td><i><%= advertisement.category.name %></i></td>
	<td><%= advertisement.created_at %></td>
	<td>
		<%= link_to "View",   advertisement_path(advertisement), class: "btn btn-primary" %> </td>
	<td>	
		<%= link_to "Edit",   edit_advertisement_path(advertisement), class: "btn btn-primary" %> </td>
	<td>
		<%= link_to "Delete", advertisement, data: {
  													confirm: 'Are you shure?'
													}, method: :delete, class: "btn btn-danger" %> 
	</td>
</tr>

app/views/advertisements/_form.html.erb
<%= form_for(@advertisement, html: { multipart: true, class: "advertisement", id: "advertisement_form"}) do |f| %>

<%= render 'shared/error_messages', object: f.object %>

<div class="categories" id="select-categories">
	<label for="categories">
		<h4 class="categories-choice">Select category</h4>
	</label>
	<br />
	<%= f.label :category, "Category: *" %><br />    
	<%= f.select(:category_id, Category.all.collect { |c| [ c.name, c.id ] }, {prompt: 'Select...'}, {id: "categories", class: "categories-select"} ) %>
</div>

<div id="form-holder" class="form-holder first_time">
	<div class="start-message" id="form-message">Please select category to continue. Thank you!</div>

	<div id="show-form">
		<hr />
			<div class="form-group">
		  	<div class="row">
		  		<div class="col-sm-4">
		    		<%= label :vehicle_brands, "Brand: *" %><br />    
		    		<%= select_tag :vehicle_brands, {}, class: "required" %>
		    	</div>

		    	<div class="col-sm-4">
		    		<%= f.label :vehicle_model, "Model: *" %><br />    
		    		<%= f.select :vehicle_model_id, {}, {}, id: "vm_select", disabled: true %>
		    	</div>
		    </div>
		  </div>

			<div class="form-group">
		    <%= f.label :title, "Title: *" %> <br />
		    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		    <%= f.label :description, "Description:" %> <br />
		    <%= f.text_area :description, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		  	<div class="row">
		  		<div class="col-sm-4">
		    		<%= f.label :price, "Price(€): *" %>    
		    		<%= f.text_field :price,  size: 20, placeholder: "000.000" %> 
		    	</div>

		    	<div class="col-sm-4">
		    		<%= f.label :year, "Year: *" %>    
		    		<%= f.text_field :year, placeholder: "Click here", id: "advertisement_year" %> 
		    	</div>
		    </div>
		  </div>

			<hr />

			<%= fields_for :advertisement_informations do |info| %>
				<h4 class="text-info">Basic information</h4>
  			<%#= f.label :capacity, "Capacity(cm3): *" %> <br />   
  			<%#= f.text_field :capacity,  size: 5, placeholder: "0000" %>
			
	  		<div id="basic_informations"></div> 
			  <hr />
			  
			  <h4 class="text-info">Additional information</h4>
			  <%#= f.label :exterior_color, "Exteriror color: *" %><br />    
	  		<%#= f.collection_select :exterior_color_id, Color.all, :id, :name, prompt: "" %>
				
				<div id="additional_informations"></div> 
	  	<% end %>	
				
			<hr />

			<%= fields_for :options do |option| %>	
		  	<h4 class="text-info">Options</h4>	
				<div id="options"></div>
			<% end %>

			<hr />
			<div class="picture">
				<h3>
				<span class="label label-info">For multiple image selection use SHIFT+SELECT or CTRL+SELECT
				</span>
				</h3>
				<br/>
				<%= image_tag(@advertisement.image_url) if @advertisement.images? %>
				<%= f.file_field :images, multiple: true, accept: 'image/jpeg,image/gif,image/png' %>
			</div>
			
			<br /><br />
			<%= f.submit "Add advertisement", class: "btn btn-primary" %>
			<br /><br />

		<% end %>
	</div><!-- show_form -->

	
</div><!-- form-holder -->	

<%= javascript_include_tag "advertisements" %>

<script>
	// $("#advertisement_images").on("change", function(){
	// 	size_in_megabytes = this.files[0].size/1024/1024;
	// 	if(size_in_megabytes > 4){
	// 		sweetAlert("Maximum file size iz 4MB. Please choose a smaller file.");
	// 	}
	// });
</script>

app/views/advertisements/create.html.erb
<h1>Advertisements#create</h1>
<p>Find me in app/views/advertisements/create.html.erb</p>

app/views/advertisements/destroy.html.erb
<h1>Advertisements#destroy</h1>
<p>Find me in app/views/advertisements/destroy.html.erb</p>

app/views/advertisements/edit.html.erb
<% provide(:title, "Edit advertisement") %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h3 class="text-muted">Edit Advertisement</h3>	
		
		<%= form_for(@advertisement, html: { class: "advertisement", id: "advertisement_form"}) do |f| %>

			<%= render 'shared/error_messages', object: f.object %>

			<div class="row">
	  		<div class="col-sm-4">
    			<h4>Category: <i><%= @advertisement.category.name %></i></h4>
				</div>
			</div>
			<hr />

			<div class="form-group">
		    <%= f.label :title, "Title: *" %> <br />
		    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		    <%= f.label :description, "Description:" %> <br />
		    <%= f.text_area :description, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		  	<div class="row">
		  		<div class="col-sm-4">
		    		<%= f.label :price, "Price(€): *" %>    
		    		<%= f.text_field :price, size: 20, placeholder: "000.000" %> 
		    	</div>

		    	<div class="col-sm-4">
		    		<%= f.label :year, "Year: *" %>    
		    		<%= f.text_field :year, placeholder: "Click here", id: "advertisement_year" %> 
		    	</div>
		    </div>
		  </div>

		  <hr />

			<h4 class="text-info">Basic information</h4>
			<br />

			<div id="basic_informations">
				<% index = 0 %>
				<%= f.fields_for :advertisement_informations, @basic_informations do |advertisement_information| %>
					<% if advertisement_information.object.items.empty? %>
							<% if index % 3 === 0 %>
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value(@advertisement),
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true
	    								%>
										</div>
							<% elsif index % 3 == 2 %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value(@advertisement),
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true 
	    								%>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value(@advertisement),
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true 
	    								%>
										</div>
							<% end %>
					<% else %>
						<% if index % 3 === 0 %>
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true   %>
										</div>
							<% elsif index % 3 == 2 %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true   %>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}", required: true   %>
										</div>
							<% end %>
					<% end %>
					
					<% index = index.to_i + 1 %>
				<% end %>
			</div><!-- basic_information -->

			<hr />

			<h4 class="text-info">Additional information</h4>
			<br />

			<div id="additional_informations">
				<% index = 0 %>
				<%= f.fields_for :advertisement_informations, @additional_informations do |advertisement_information| %>
					<% if advertisement_information.object.items.empty? %>
							<% if index % 3 === 0 %>
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value,
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}" 
	    								%>
										</div>
							<% elsif index % 3 == 2 %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value,
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}" 
	    								%>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
	    								<%= text_field_tag :value, 
	    										advertisement_information.object.find_advertisement_information_value,
	    										name:"advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}" 
	    								%>
										</div>
							<% end %>
					<% else %>

						<% if index % 3 === 0 %>
								
								<div class='form-group'>
									<div class='row'>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}"   %>
										</div>
							<% elsif index % 3 == 2 %>
										
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}"   %>
										</div>
									</div>
								</div>		
							<% else %>
										<div class='col-sm-4'>
											<%= advertisement_information.label advertisement_information.object.name %><br />
											<%= select_tag "advertisement[advertisement_informations][#{advertisement_information.object.id.to_s}]", options_from_collection_for_select(advertisement_information.object.items, 
	    									"id", "name", selected: advertisement_information.object.get_advertisement_information_item(@advertisement)), 
	    										name: "advertisement[advertisement_informations][#{advertisement_information.object.id}]", id: "advertisement_advertisement_informations_#{advertisement_information.object.name}"   %>
										</div>
							<% end %>
					<% end %>
					
					<% index = index.to_i + 1 %>
				<% end %>
			</div><!-- basic_information -->

			<hr />

			<h4 class="text-info">Options</h4>	
	  	<br />	  	
	  	<div id="options">
	  	<% index = 0 %>
	  	<%= f.fields_for :options, @all_options do |option| %>	
					<% if index % 4 === 0 %>
						<div class='form-group'>
							<div class='row'>
								<div class='col-sm-3'>
									<div class='checkbox'>
										<label>
											<%= option.check_box :name, multiple: true, checked: option.object.advertisement_ids.include?(@advertisement.id) %>
											<%= option.object.name %>
										</label>
									</div>
								</div>
					<% elsif index % 4 === 3 %>
								<div class='col-sm-3'>
									<div class='checkbox'>
										<label>
											<%= option.check_box :name, multiple: true, checked: option.object.advertisement_ids.include?(@advertisement.id) %>
											<%= option.object.name %>
										</label>	
									</div>
								</div>
							</div>
						</div>
					<% else %>
								<div class='col-sm-3'>
									<div class='checkbox'>
										<label>
											<%= option.check_box :name, multiple: true, checked: option.object.advertisement_ids.include?(@advertisement.id) %>
											<%= option.object.name %>
										</label>
									</div>
								</div>
					<% end %>						
				<% index = index.to_i + 1 %>
			<% end %>
			</div>

			<hr />
			<div class="picture">
				<h3>
				<span class="label label-info">For multiple image selection use SHIFT+SELECT or CTRL+SELECT
				</span>
				</h3>
				<br/>
				<%= f.file_field :images, multiple: true, accept: 'image/jpeg,image/gif,image/png' %>
			</div>

			<br /><br />
			<%= f.submit "Edit advertisement", class: "btn btn-primary" %>
			<br /><br />
				
			<hr />

		<% end %>
		
	</div>
</div>	

<%= javascript_include_tag "advertisements" %>

app/views/advertisements/index.html.erb
<% provide(:title, "All Advertisements") %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<div class="list-group">
  		<h3>Yours Advertisements</h3>
  		<br />
      <%= link_to "New Advertisement", new_advertisement_path, class: "btn btn-primary" %> </td>
      <hr />
			<div class="table-responsive">
  			<table class="table table-striped table-hover">
  				<thead>
  					<tr>
  						<th>Title</th>
  						<th>Category</th>
  						<th>Date</th>
  					</tr>
  				</thead>
  				<tbody>
    				<%= render @advertisements %>
    			</tbody>
  			</table>
			</div>
		</div>
</div>
</div>

app/views/advertisements/new.html.erb
<% provide(:title, "New advertisement") %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h3 class="text-muted">New Advertisement</h3>	
		
		<%= render 'form' %>

		<div class="text-center" id="spinner"></div>
		
	</div>
</div>	

app/views/advertisements/show.html.erb
<% provide(:title, "Advertisement detail") %>

<h3><td><%= @advertisement.title %></td></h3>
<hr />

<div class="row">
  <div class="col-sm-8">
    <% if !@advertisement.images.empty? %>
      <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
      </div>

      <div id="links" class="">
        <% @advertisement.images.each_with_index do |image, index| %>
          <%= link_to image.url do %>
            <%= image_tag image.thumb_middle.url, class: "img-thumbnail" %>
          <% end %>
        <% end %>
      </div>
    <% else %>
        <%= image_tag "placeholder.png", class: "img-responsive no-image-placeholder" %>
    <% end %>
  </div>

  <div class="col-sm-4">
    <div class="infos">
      <p><b>Model:</b> <%= @advertisement.vehicle_model.name %></p>
      <p><b>Brand:</b> <%= @advertisement.vehicle_model.vehicle_brand.name %></p>
      <p><b>Category:</b> <%= @advertisement.category.name %></p>
      <p><b>Price:</b> <%= number_with_precision @advertisement.price, precision: 2 %> €</p>
      <p><b>Year:</b> <%= @advertisement.year %></p>
      <p><b>Added:</b> <%= time_ago_in_words @advertisement.created_at %> ago.</p>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-md-8">
    <h3>Basic information</h3>

    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <tbody>
          <% @basic_advertisement_informations.each do |key, value| %>
            <tr>
              <td><b><%= key %>:</b></td>
              <td><%= value %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>  
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h3>Additional information</h3>

    <% if @additional_advertisement_informations.length > 0 %> 
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <tbody>
            <% @additional_advertisement_informations.each do |key, value| %>
              <tr>
                <td><b><%= key %>:</b></td>
                <td><%= value %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div> 
    <% else %>
      <h4>No additional information!</h4>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h3>Options</h3>

    <% if @advertisement.options.size > 0 %>
      <ul>
        <% @advertisement.options.each do |option| %>
          <li><%= option.name %></li>
        <% end %>
      </ul> 
    <% else %>
      <div class="alert alert-info" role="alert">There is no options!</div>
    <% end %> 

  </div>
</div>

<div class="row">
  <div class="col-md-8 comments-page">    
    <h3>Comments</h3><br/>

    <%= react_component('CommentSection', comments: raw(render(template: 'comments/index.json.jbuilder')),
                                          advertisementId: @advertisement.id ) %>

  </div>
</div>


<script>
var links = document.getElementById('links');
if(links) {
  links.onclick = function (event) {
      event = event || window.event;
      var target = event.target || event.srcElement,
          link = target.src ? target.parentNode : target,
          options = {index: link, event: event},
          links = this.getElementsByTagName('a');
      blueimp.Gallery(links, options);
  };
}  

var fullscreenOptions = {
    // Defines if the gallery should open in fullscreen mode:
    fullScreen: false
};
</script>

app/views/advertisements/update.html.erb
<h1>Advertisements#update</h1>
<p>Find me in app/views/advertisements/update.html.erb</p>