config/routes.rb
Rails.application.routes.draw do
  get 'informations/index'

  get 'categories/index'

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'static_pages#home'

  get  'help'   => 'static_pages#help'
  get  'about'   => 'static_pages#about'
  get  'contact' => 'static_pages#contact'

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: :show  
  resources :vehicle_models
  resources :vehicle_brands, only: [:index, :show]
  resources :options
  resources :advertisements do
    resources :comments do
      put 'upvote', to: 'comments#upvote'
    end
  end


  resources :categories, only: [:index, :show] do
    member do
      get "basic", to: "categories#basic"
      get "additional", to: "categories#additional"
      get "options", to: "categories#options"

      resources :advertisements, only: :show 
    end
  end

  resources :information, only: :index do
    member do
      get 'items', to: 'informations#items'  
    end  
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		MG Advertisment by Miroslav Gojic. <%= link_to "Contact email", 'mailto: miroslav.gojic.78@gmail.com' %>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
<nav class="navbar navbar-default back-pad">
	<div class="container-fluid">
		<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mg Advertisement", root_path, id: "logo" %>
    </div>
		
		<div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">  	
      	<% if user_signed_in? %>
      		<li class="header-link"><em><%= link_to current_user.email, current_user %></em></li>
      		<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Advertisements <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Add advertisement', new_advertisement_path %></li>
							<li class="divider"></li>
							<li><%= link_to 'All Advertisements', advertisements_path %></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Profile', current_user %></li>
							<li><%= link_to 'Settings', edit_user_registration_path %></li>
							<li class="divider"></li>
							<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
				<% else %>
					<li>
      			<%= render 'devise/forms/session_form' %>
      		</li>
					<li><%= link_to "Log In", new_user_session_path %></li>
					<li><%= link_to "Register", new_user_registration_path %></li>
				<% end %>	
      </ul>
		</div><!--/.nav-collapse -->

	</div><!--/.container-fluid -->
</nav>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="<%= flash_class name %> mg-tp-10">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
	
<div class="container">
	<div class="front-bg">
		<%= image_tag("background.png", alt: "Rails logo") %>
	</div>
	
	<%= render "layouts/header" %>
	
	<div class="container">
		<div class="backg-cont">
			<%= render 'layouts/messages' %>	

			<%= yield %>

			<%= render 'layouts/footer' %>
		
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</div>

</body>
</html>